name: Enforce Test Coverage

on:
  pull_request:
    branches: [main, dev]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Jest with coverage
        run: npx jest --coverage

      - name: Check coverage threshold (fail under 50%)
        run: |
          COVERAGE=$(npx jest --coverage --json --outputFile=coverage.json && cat coverage/coverage-summary.json | grep "lines" | awk '{print $2}' | tr -d ',')
          echo "Lines coverage: $COVERAGE"
          COVERAGE_INT=${COVERAGE%.*}
          if [ "$COVERAGE_INT" -lt 50 ]; then
            echo "❌ Coverage is below 50%!"
            exit 1
          else
            echo "✅ Coverage is acceptable."
          fi
